### Future

---

*scala.concurrent* 包里的 `Future[T]` 是一个容器类型，代表一种返回值类型为 `T` 的计算。 计算可能会出错，也可能会超时；从而，当一个 future 完成时，它可能会包含异常，而不是你期望的那个值。

Future 只能写一次： 当一个 future 完成后，它就不能再被改变了。 同时，Future 只提供了读取计算值的接口，写入计算值的任务交给了 Promise，这样，API 层面上会有一个清晰的界限。 这篇文章里，我们主要关注前者，下一章会介绍 Promise 的使用。

首先，所有可以并行执行的函数，应该返回一个 Future：

```scala
import scala.concurrent.future
import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration._
import scala.util.Random

def grind(beans: CoffeeBeans): Future[GroundCoffee] = Future {
  println("start grinding...")
  Thread.sleep(Random.nextInt(2000))
  if (beans == "baked beans") throw GrindingException("are you joking?")
  println("finished grinding...")
  s"ground coffee of $beans"
}

def heatWater(water: Water): Future[Water] = Future {
  println("heating the water now")
  Thread.sleep(Random.nextInt(2000))
  println("hot, it's hot!")
  water.copy(temperature = 85)
}

def frothMilk(milk: Milk): Future[FrothedMilk] = Future {
  println("milk frothing system engaged!")
  Thread.sleep(Random.nextInt(2000))
  println("shutting down milk frothing system")
  s"frothed $milk"
}

def brew(coffee: GroundCoffee, heatedWater: Water): Future[Espresso] = Future {
  println("happy brewing :)")
  Thread.sleep(Random.nextInt(2000))
  println("it's brewed!")
  "espresso"
}
```

##### 回调

对于一些简单的问题，使用回调就能很好解决。 Future 的回调是偏函数，你可以把回调传递给 Future 的 `onSuccess` 方法， 如果这个 Future 成功完成，这个回调就会执行，并把 Future 的返回值作为参数输入：

```
 grind("arabica beans").onSuccess { case ground =>
   println("okay, got my ground coffee")
 }

```

类似的，也可以在 `onFailure` 上注册回调，只不过它是在 Future 失败时调用，其输入是一个 `Throwable`。

通常的做法是将两个回调结合在一起以更好的处理 Future：在 `onComplete` 方法上注册回调，回调的输入是一个 Try。

```
 import scala.util.{Success, Failure}
 grind("baked beans").onComplete {
   case Success(ground) => println(s"got my $ground")
   case Failure(ex) => println("This grinder needs a replacement, seriously!")
 }

```

传递给 `grind` 的是 “baked beans”，因此 `grind` 方法会产生异常，进而导致 Future 中的计算失败。

---

#### Future 组合

